query getQuestDrops($partialName: String!, $type: QuestAreaType!) {
    quest(partialName: $partialName, type: $type) {
        waveGroups {
            possibleWaves {
                rate
                drops: enemies {
                    by: enemy {
                        name
                        unit {
                            id
                        }
                    }
                    mana: dropMana
                    reward: dropReward {
                        rate
                        ... on DropEquipment {
                            count
                            equipment {
                                id
                                name
                            }
                        }
                        ... on DropItem {
                            count
                            item {
                                id
                                name
                            }
                        }
                    }
                }
            }
        }
    }
}
